
import java.io.File;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Johansen
 */
public class pengaturan extends javax.swing.JFrame {

    /**
     * Creates new form pengaturan
     */
    public pengaturan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPengaturan = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        labelWarna = new javax.swing.JLabel();
        comboWarna = new javax.swing.JComboBox<>();
        buttonSimpanPerubahan = new javax.swing.JButton();
        buttonKembali1 = new javax.swing.JButton();
        labelUkuran = new javax.swing.JLabel();
        labelJenis = new javax.swing.JLabel();
        labelTebal = new javax.swing.JLabel();
        comboUkuran = new javax.swing.JComboBox<>();
        comboJenis = new javax.swing.JComboBox<>();
        comboTebal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Input Data Mahasiswa");

        panelPengaturan.setBackground(new java.awt.Color(102, 102, 255));
        panelPengaturan.setForeground(new java.awt.Color(255, 255, 255));

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul.setText("Pengaturan");

        labelWarna.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        labelWarna.setForeground(new java.awt.Color(255, 255, 255));
        labelWarna.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWarna.setText("Warna Background:");

        comboWarna.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        comboWarna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Biru", "Kuning", "Merah", "Hijau"}));
        comboWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWarnaActionPerformed(evt);
            }
        });

        buttonSimpanPerubahan.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonSimpanPerubahan.setText("Simpan Perubahan");
        buttonSimpanPerubahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanPerubahanActionPerformed(evt);
            }
        });

        buttonKembali1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonKembali1.setText("Kembali ke Menu Utama");
        buttonKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembali1ActionPerformed(evt);
            }
        });

        labelUkuran.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        labelUkuran.setForeground(new java.awt.Color(255, 255, 255));
        labelUkuran.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUkuran.setText("Ukuran Huruf:");

        labelJenis.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        labelJenis.setForeground(new java.awt.Color(255, 255, 255));
        labelJenis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJenis.setText("Jenis Huruf:");

        labelTebal.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        labelTebal.setForeground(new java.awt.Color(255, 255, 255));
        labelTebal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTebal.setText("Ketebalan Huruf:");

        comboUkuran.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        comboUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Kecil", "Standar", "Besar"}));
        comboUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUkuranActionPerformed(evt);
            }
        });

        comboJenis.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        comboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Verdana", "Impact", "Times New Roman"}));
        comboJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJenisActionPerformed(evt);
            }
        });

        comboTebal.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        comboTebal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Standar", "Tebal"}));
        comboTebal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTebalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPengaturanLayout = new javax.swing.GroupLayout(panelPengaturan);
        panelPengaturan.setLayout(panelPengaturanLayout);
        panelPengaturanLayout.setHorizontalGroup(
            panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPengaturanLayout.createSequentialGroup()
                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPengaturanLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(labelJudul))
                    .addGroup(panelPengaturanLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPengaturanLayout.createSequentialGroup()
                                .addComponent(labelWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPengaturanLayout.createSequentialGroup()
                                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTebal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTebal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPengaturanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPengaturanLayout.createSequentialGroup()
                        .addComponent(buttonKembali1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPengaturanLayout.createSequentialGroup()
                        .addComponent(buttonSimpanPerubahan)
                        .addGap(196, 196, 196))))
        );
        panelPengaturanLayout.setVerticalGroup(
            panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPengaturanLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelJudul)
                .addGap(31, 31, 31)
                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWarna)
                    .addComponent(comboWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUkuran)
                    .addComponent(comboUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJenis))
                .addGap(18, 18, 18)
                .addGroup(panelPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTebal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTebal))
                .addGap(18, 18, 18)
                .addComponent(buttonSimpanPerubahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(buttonKembali1)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboWarnaActionPerformed

    private void buttonSimpanPerubahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanPerubahanActionPerformed
            // TODO add your handling code here:
            int response = JOptionPane.showConfirmDialog(this, "Simpan Perubahan?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.YES_OPTION){
                if(comboWarna.getSelectedItem().equals("Biru")){
                    panelPengaturan.setBackground(new java.awt.Color(102, 102, 255));
                }
                else if(comboWarna.getSelectedItem().equals("Kuning")){
                    panelPengaturan.setBackground(new java.awt.Color(255, 255, 102));
                }
                else if(comboWarna.getSelectedItem().equals("Merah")){
                    panelPengaturan.setBackground(new java.awt.Color(255, 51, 51));
                }   
                else if(comboWarna.getSelectedItem().equals("Hijau")){
                    panelPengaturan.setBackground(new java.awt.Color(51, 255, 51));
                }
                
                if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Kecil") && comboJenis.getSelectedItem().equals("Verdana")){
                    labelJudul.setFont(new java.awt.Font("Verdana", 0, 9));
                    labelWarna.setFont(new java.awt.Font("Verdana", 0, 9));
                    labelUkuran.setFont(new java.awt.Font("Verdana", 0, 9));
                    labelJenis.setFont(new java.awt.Font("Verdana", 0, 9));
                    labelTebal.setFont(new java.awt.Font("Verdana", 0, 9));
                    comboWarna.setFont(new java.awt.Font("Verdana", 0, 9));
                    comboUkuran.setFont(new java.awt.Font("Verdana", 0, 9));
                    comboJenis.setFont(new java.awt.Font("Verdana", 0, 9));
                    comboTebal.setFont(new java.awt.Font("Verdana", 0, 9));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Verdana", 0, 9));
                    buttonKembali1.setFont(new java.awt.Font("Verdana", 0, 9));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Kecil") && comboJenis.getSelectedItem().equals("Impact")){
                    labelJudul.setFont(new java.awt.Font("Impact", 0, 9));
                    labelWarna.setFont(new java.awt.Font("Impact", 0, 9));
                    labelUkuran.setFont(new java.awt.Font("Impact", 0, 9));
                    labelJenis.setFont(new java.awt.Font("Impact", 0, 9));
                    labelTebal.setFont(new java.awt.Font("Impact", 0, 9));
                    comboWarna.setFont(new java.awt.Font("Impact", 0, 9));
                    comboUkuran.setFont(new java.awt.Font("Impact", 0, 9));
                    comboJenis.setFont(new java.awt.Font("Impact", 0, 9));
                    comboTebal.setFont(new java.awt.Font("Impact", 0, 9));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Impact", 0, 9));
                    buttonKembali1.setFont(new java.awt.Font("Impact", 0, 9));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Kecil") && comboJenis.getSelectedItem().equals("Times New Roman")){
                    labelJudul.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    labelWarna.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    labelUkuran.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    labelJenis.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    labelTebal.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    comboWarna.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    comboUkuran.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    comboJenis.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    comboTebal.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Times New Roman", 0, 9));
                    buttonKembali1.setFont(new java.awt.Font("Times New Roman", 0, 9));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Standar") && comboJenis.getSelectedItem().equals("Verdana")){
                    labelJudul.setFont(new java.awt.Font("Verdana", 0, 11));
                    labelWarna.setFont(new java.awt.Font("Verdana", 0, 11));
                    labelUkuran.setFont(new java.awt.Font("Verdana", 0, 11));
                    labelJenis.setFont(new java.awt.Font("Verdana", 0, 11));
                    labelTebal.setFont(new java.awt.Font("Verdana", 0, 11));
                    comboWarna.setFont(new java.awt.Font("Verdana", 0, 11));
                    comboUkuran.setFont(new java.awt.Font("Verdana", 0, 11));
                    comboJenis.setFont(new java.awt.Font("Verdana", 0, 11));
                    comboTebal.setFont(new java.awt.Font("Verdana", 0, 11));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Verdana", 0, 11));
                    buttonKembali1.setFont(new java.awt.Font("Verdana", 0, 11));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Standar") && comboJenis.getSelectedItem().equals("Impact")){
                    labelJudul.setFont(new java.awt.Font("Impact", 0, 11));
                    labelWarna.setFont(new java.awt.Font("Impact", 0, 11));
                    labelUkuran.setFont(new java.awt.Font("Impact", 0, 11));
                    labelJenis.setFont(new java.awt.Font("Impact", 0, 11));
                    labelTebal.setFont(new java.awt.Font("Impact", 0, 11));
                    comboWarna.setFont(new java.awt.Font("Impact", 0, 11));
                    comboUkuran.setFont(new java.awt.Font("Impact", 0, 11));
                    comboJenis.setFont(new java.awt.Font("Impact", 0, 11));
                    comboTebal.setFont(new java.awt.Font("Impact", 0, 11));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Impact", 0, 11));
                    buttonKembali1.setFont(new java.awt.Font("Impact", 0, 11));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Standar") && comboJenis.getSelectedItem().equals("Times New Roman")){
                    labelJudul.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    labelWarna.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    labelUkuran.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    labelJenis.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    labelTebal.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    comboWarna.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    comboUkuran.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    comboJenis.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    comboTebal.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Times New Roman", 0, 11));
                    buttonKembali1.setFont(new java.awt.Font("Times New Roman", 0, 11));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Besar") && comboJenis.getSelectedItem().equals("Verdana")){
                    labelJudul.setFont(new java.awt.Font("Verdana", 0, 13));
                    labelWarna.setFont(new java.awt.Font("Verdana", 0, 13));
                    labelUkuran.setFont(new java.awt.Font("Verdana", 0, 13));
                    labelJenis.setFont(new java.awt.Font("Verdana", 0, 13));
                    labelTebal.setFont(new java.awt.Font("Verdana", 0, 13));
                    comboWarna.setFont(new java.awt.Font("Verdana", 0, 13));
                    comboUkuran.setFont(new java.awt.Font("Verdana", 0, 13));
                    comboJenis.setFont(new java.awt.Font("Verdana", 0, 13));
                    comboTebal.setFont(new java.awt.Font("Verdana", 0, 13));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Verdana", 0, 13));
                    buttonKembali1.setFont(new java.awt.Font("Verdana", 0, 13));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Besar") && comboJenis.getSelectedItem().equals("Impact")){
                    labelJudul.setFont(new java.awt.Font("Impact", 0, 13));
                    labelWarna.setFont(new java.awt.Font("Impact", 0, 13));
                    labelUkuran.setFont(new java.awt.Font("Impact", 0, 13));
                    labelJenis.setFont(new java.awt.Font("Impact", 0, 13));
                    labelTebal.setFont(new java.awt.Font("Impact", 0, 13));
                    comboWarna.setFont(new java.awt.Font("Impact", 0, 13));
                    comboUkuran.setFont(new java.awt.Font("Impact", 0, 13));
                    comboJenis.setFont(new java.awt.Font("Impact", 0, 13));
                    comboTebal.setFont(new java.awt.Font("Impact", 0, 13));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Impact", 0, 13));
                    buttonKembali1.setFont(new java.awt.Font("Impact", 0, 13));
                }
                else if(comboTebal.getSelectedItem().equals("Standar") && comboUkuran.getSelectedItem().equals("Besar") && comboJenis.getSelectedItem().equals("Times New Roman")){
                    labelJudul.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    labelWarna.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    labelUkuran.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    labelJenis.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    labelTebal.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    comboWarna.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    comboUkuran.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    comboJenis.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    comboTebal.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Times New Roman", 0, 13));
                    buttonKembali1.setFont(new java.awt.Font("Times New Roman", 0, 13));
                }
                //checkpoint
                //checkpoint
                //checkpoint
                //checkpoint
                //checkpoint
                //checkpoint
                //checkpoint
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Kecil") && comboJenis.getSelectedItem().equals("Verdana")){
                    labelJudul.setFont(new java.awt.Font("Verdana", 1, 9));
                    labelWarna.setFont(new java.awt.Font("Verdana", 1, 9));
                    labelUkuran.setFont(new java.awt.Font("Verdana", 1, 9));
                    labelJenis.setFont(new java.awt.Font("Verdana", 1, 9));
                    labelTebal.setFont(new java.awt.Font("Verdana", 1, 9));
                    comboWarna.setFont(new java.awt.Font("Verdana", 1, 9));
                    comboUkuran.setFont(new java.awt.Font("Verdana", 1, 9));
                    comboJenis.setFont(new java.awt.Font("Verdana", 1, 9));
                    comboTebal.setFont(new java.awt.Font("Verdana", 1, 9));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Verdana", 1, 9));
                    buttonKembali1.setFont(new java.awt.Font("Verdana", 1, 9));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Kecil") && comboJenis.getSelectedItem().equals("Impact")){
                    labelJudul.setFont(new java.awt.Font("Impact", 1, 9));
                    labelWarna.setFont(new java.awt.Font("Impact", 1, 9));
                    labelUkuran.setFont(new java.awt.Font("Impact", 1, 9));
                    labelJenis.setFont(new java.awt.Font("Impact", 1, 9));
                    labelTebal.setFont(new java.awt.Font("Impact", 1, 9));
                    comboWarna.setFont(new java.awt.Font("Impact", 1, 9));
                    comboUkuran.setFont(new java.awt.Font("Impact", 1, 9));
                    comboJenis.setFont(new java.awt.Font("Impact", 1, 9));
                    comboTebal.setFont(new java.awt.Font("Impact", 1, 9));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Impact", 1, 9));
                    buttonKembali1.setFont(new java.awt.Font("Impact", 1, 9));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Kecil") && comboJenis.getSelectedItem().equals("Times New Roman")){
                    labelJudul.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    labelWarna.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    labelUkuran.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    labelJenis.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    labelTebal.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    comboWarna.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    comboUkuran.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    comboJenis.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    comboTebal.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Times New Roman", 1, 9));
                    buttonKembali1.setFont(new java.awt.Font("Times New Roman", 1, 9));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Standar") && comboJenis.getSelectedItem().equals("Verdana")){
                    labelJudul.setFont(new java.awt.Font("Verdana", 1, 11));
                    labelWarna.setFont(new java.awt.Font("Verdana", 1, 11));
                    labelUkuran.setFont(new java.awt.Font("Verdana", 1, 11));
                    labelJenis.setFont(new java.awt.Font("Verdana", 1, 11));
                    labelTebal.setFont(new java.awt.Font("Verdana", 1, 11));
                    comboWarna.setFont(new java.awt.Font("Verdana", 1, 11));
                    comboUkuran.setFont(new java.awt.Font("Verdana", 1, 11));
                    comboJenis.setFont(new java.awt.Font("Verdana", 1, 11));
                    comboTebal.setFont(new java.awt.Font("Verdana", 1, 11));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Verdana", 1, 11));
                    buttonKembali1.setFont(new java.awt.Font("Verdana", 1, 11));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Standar") && comboJenis.getSelectedItem().equals("Impact")){
                    labelJudul.setFont(new java.awt.Font("Impact", 1, 11));
                    labelWarna.setFont(new java.awt.Font("Impact", 1, 11));
                    labelUkuran.setFont(new java.awt.Font("Impact", 1, 11));
                    labelJenis.setFont(new java.awt.Font("Impact", 1, 11));
                    labelTebal.setFont(new java.awt.Font("Impact", 1, 11));
                    comboWarna.setFont(new java.awt.Font("Impact", 1, 11));
                    comboUkuran.setFont(new java.awt.Font("Impact", 1, 11));
                    comboJenis.setFont(new java.awt.Font("Impact", 1, 11));
                    comboTebal.setFont(new java.awt.Font("Impact", 1, 11));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Impact", 1, 11));
                    buttonKembali1.setFont(new java.awt.Font("Impact", 1, 11));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Standar") && comboJenis.getSelectedItem().equals("Times New Roman")){
                    labelJudul.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    labelWarna.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    labelUkuran.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    labelJenis.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    labelTebal.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    comboWarna.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    comboUkuran.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    comboJenis.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    comboTebal.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Times New Roman", 1, 11));
                    buttonKembali1.setFont(new java.awt.Font("Times New Roman", 1, 11));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Besar") && comboJenis.getSelectedItem().equals("Verdana")){
                    labelJudul.setFont(new java.awt.Font("Verdana", 1, 13));
                    labelWarna.setFont(new java.awt.Font("Verdana", 1, 13));
                    labelUkuran.setFont(new java.awt.Font("Verdana", 1, 13));
                    labelJenis.setFont(new java.awt.Font("Verdana", 1, 13));
                    labelTebal.setFont(new java.awt.Font("Verdana", 1, 13));
                    comboWarna.setFont(new java.awt.Font("Verdana", 1, 13));
                    comboUkuran.setFont(new java.awt.Font("Verdana", 1, 13));
                    comboJenis.setFont(new java.awt.Font("Verdana", 1, 13));
                    comboTebal.setFont(new java.awt.Font("Verdana", 1, 13));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Verdana", 1, 13));
                    buttonKembali1.setFont(new java.awt.Font("Verdana", 1, 13));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Besar") && comboJenis.getSelectedItem().equals("Impact")){
                    labelJudul.setFont(new java.awt.Font("Impact", 1, 13));
                    labelWarna.setFont(new java.awt.Font("Impact", 1, 13));
                    labelUkuran.setFont(new java.awt.Font("Impact", 1, 13));
                    labelJenis.setFont(new java.awt.Font("Impact", 1, 13));
                    labelTebal.setFont(new java.awt.Font("Impact", 1, 13));
                    comboWarna.setFont(new java.awt.Font("Impact", 1, 13));
                    comboUkuran.setFont(new java.awt.Font("Impact", 1, 13));
                    comboJenis.setFont(new java.awt.Font("Impact", 1, 13));
                    comboTebal.setFont(new java.awt.Font("Impact", 1, 13));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Impact", 1, 13));
                    buttonKembali1.setFont(new java.awt.Font("Impact", 1, 13));
                }
                else if(comboTebal.getSelectedItem().equals("Tebal") && comboUkuran.getSelectedItem().equals("Besar") && comboJenis.getSelectedItem().equals("Times New Roman")){
                    labelJudul.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    labelWarna.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    labelUkuran.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    labelJenis.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    labelTebal.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    comboWarna.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    comboUkuran.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    comboJenis.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    comboTebal.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    buttonSimpanPerubahan.setFont(new java.awt.Font("Times New Roman", 1, 13));
                    buttonKembali1.setFont(new java.awt.Font("Times New Roman", 1, 13));
                }
            }
            else if (response == JOptionPane.NO_OPTION){
            }
            
            
    }//GEN-LAST:event_buttonSimpanPerubahanActionPerformed

    private void buttonKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembali1ActionPerformed
        // TODO add your handling code here:
        dispose();
        menuUtama menu = new menuUtama();
        menu.setVisible(true);
    }//GEN-LAST:event_buttonKembali1ActionPerformed

    private void comboUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUkuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUkuranActionPerformed

    private void comboJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJenisActionPerformed

    private void comboTebalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTebalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTebalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengaturan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali1;
    public static javax.swing.JButton buttonSimpanPerubahan;
    private javax.swing.JComboBox<String> comboJenis;
    private javax.swing.JComboBox<String> comboTebal;
    private javax.swing.JComboBox<String> comboUkuran;
    private javax.swing.JComboBox<String> comboWarna;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelTebal;
    private javax.swing.JLabel labelUkuran;
    private javax.swing.JLabel labelWarna;
    private javax.swing.JPanel panelPengaturan;
    // End of variables declaration//GEN-END:variables
}
