/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Johansen
 */
public class tambahan extends javax.swing.JFrame {

    /**
     * Creates new form tambahan
     */
    public tambahan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        nama3 = new javax.swing.JLabel();
        nama4 = new javax.swing.JLabel();
        nama5 = new javax.swing.JLabel();
        nama6 = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        nama7 = new javax.swing.JLabel();
        nama8 = new javax.swing.JLabel();
        nama9 = new javax.swing.JLabel();
        nama10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Input Data Mahasiswa");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul.setText("Apa yang Kami Ubah/Tambah?");

        nama.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama.setText("1. Warna background diubah menjadi biru.");
        nama.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama1.setForeground(new java.awt.Color(255, 255, 255));
        nama1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama1.setText("2. Pengaturan pada tabel dibagian tabel data dan tabel kami ubah menjadi disabled, kemudian kami tambahkan:");
        nama1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama2.setForeground(new java.awt.Color(255, 255, 255));
        nama2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama2.setText("- Tombol edit, untuk mengubah pengaturan tabel menjadi enabled.");
        nama2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama3.setForeground(new java.awt.Color(255, 255, 255));
        nama3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama3.setText("3. Terdapat dua opsi ketika akan menghapus data ataupun nilai, yaitu yes dan no.");
        nama3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama4.setForeground(new java.awt.Color(255, 255, 255));
        nama4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama4.setText("- Tombol simpan perubahan, untuk mengubah pengaturan tabel menjadi disabled.");
        nama4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama5.setForeground(new java.awt.Color(255, 255, 255));
        nama5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama5.setText("4. Tombol kembali ke menu utama pada setiap frame.");
        nama5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama6.setForeground(new java.awt.Color(255, 255, 255));
        nama6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama6.setText("5. Pergantian frame akan menutup frame yang terbuka.");
        nama6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonKembali.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonKembali.setText("Kembali ke Menu Utama");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        nama7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama7.setForeground(new java.awt.Color(255, 255, 255));
        nama7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama7.setText("6. Menu pengaturan, untuk mengubah beberapa tampilan di frame pengaturan. (Mohon maaf, kami kurang");
        nama7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama8.setForeground(new java.awt.Color(255, 255, 255));
        nama8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama8.setText("memahami cara untuk mengubah layout di semua frame melalui satu frame saja.");
        nama8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama9.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama9.setForeground(new java.awt.Color(255, 255, 255));
        nama9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama9.setText("7. Menu tentang, untuk menampilkan nama-nama anggota kelompok, dan tanggal pengerjaan");
        nama9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nama10.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        nama10.setForeground(new java.awt.Color(255, 255, 255));
        nama10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama10.setText("8. Terdapat tampilan konfirmasi keluar ketika akan keluar dari aplikasi menggunakan tombol keluar.");
        nama10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(labelJudul))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nama4, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(nama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nama3, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama5, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama6, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nama8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nama10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonKembali)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(buttonKembali)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        menuUtama menu = new menuUtama();
        menu.setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama10;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JLabel nama4;
    private javax.swing.JLabel nama5;
    private javax.swing.JLabel nama6;
    private javax.swing.JLabel nama7;
    private javax.swing.JLabel nama8;
    private javax.swing.JLabel nama9;
    // End of variables declaration//GEN-END:variables
}
