/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Johansen
 */
public class tentang extends javax.swing.JFrame {

    /**
     * Creates new form tentang
     */
    public tentang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        labelJudul1 = new javax.swing.JLabel();
        labelJudul5 = new javax.swing.JLabel();
        labelJudul6 = new javax.swing.JLabel();
        labelJudul7 = new javax.swing.JLabel();
        labelJudul9 = new javax.swing.JLabel();
        labelJudul11 = new javax.swing.JLabel();
        labelJudul12 = new javax.swing.JLabel();
        labelJudul13 = new javax.swing.JLabel();
        labelJudul14 = new javax.swing.JLabel();
        labelJudul15 = new javax.swing.JLabel();
        labelJudul16 = new javax.swing.JLabel();
        labelJudul17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Input Data Mahasiswa");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul.setText("Nama Anggota Kelompok:");

        buttonKembali.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonKembali.setText("Kembali ke Menu Utama");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        labelJudul1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul1.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJudul1.setText("1. Johansen Sagala (NIM: 2081031)");

        labelJudul5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul5.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul5.setText("2. Lizki Silaban (NIM: 2081016)");

        labelJudul6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul6.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul6.setText("3. Nicholas Manurung (NIM: 2081015)");

        labelJudul7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul7.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul7.setText("Mulai dikerjakan tanggal 03 Desember 2021 dan selesai dikerjakan tanggal 05 Desember 2021");

        labelJudul9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul9.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul9.setText("Membuat menu \"tentang\" , membantu mengkoreksi coding, memberi ide-ide program.");

        labelJudul11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul11.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJudul11.setText("Membuat menu \"tambahan\", membantu mengkoreksi, mencari ide-ide tambahan");

        labelJudul12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul12.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelJudul13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul13.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelJudul14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul14.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        labelJudul15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul15.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        labelJudul16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul16.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        labelJudul17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul17.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJudul17.setText("Membuat menu \"splash screen\", \"menu utama\", \"input nilai\", \"input data\", \"pengaturan\", tombol-tombol lainnya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelJudul6)
                                .addGap(192, 192, 192)
                                .addComponent(labelJudul12, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelJudul5)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(labelJudul1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelJudul13)))
                                        .addGap(470, 470, 470))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelJudul17)
                                        .addGap(18, 18, 18)))
                                .addComponent(labelJudul15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJudul16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelJudul7)
                                    .addComponent(labelJudul9, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(labelJudul11, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(labelJudul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonKembali)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(labelJudul14)
                    .addContainerGap(839, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelJudul)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelJudul13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addComponent(labelJudul1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(labelJudul17, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJudul5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJudul11, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(labelJudul15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelJudul16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelJudul12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelJudul9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJudul6)))
                .addGap(29, 29, 29)
                .addComponent(labelJudul7)
                .addGap(60, 60, 60)
                .addComponent(buttonKembali)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(labelJudul14, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addGap(94, 94, 94)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        menuUtama menu = new menuUtama();
        menu.setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tentang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJudul1;
    private javax.swing.JLabel labelJudul11;
    private javax.swing.JLabel labelJudul12;
    private javax.swing.JLabel labelJudul13;
    private javax.swing.JLabel labelJudul14;
    private javax.swing.JLabel labelJudul15;
    private javax.swing.JLabel labelJudul16;
    private javax.swing.JLabel labelJudul17;
    private javax.swing.JLabel labelJudul5;
    private javax.swing.JLabel labelJudul6;
    private javax.swing.JLabel labelJudul7;
    private javax.swing.JLabel labelJudul9;
    // End of variables declaration//GEN-END:variables
}
